/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tinta_common_lua_tintaLua */

#ifndef _Included_com_tinta_common_lua_tintaLua
#define _Included_com_tinta_common_lua_tintaLua
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tinta_common_lua_tintaLua_init
  (JNIEnv *, jobject);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tinta_common_lua_tintaLua_release
  (JNIEnv *, jobject);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    executeBuffer
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_tinta_common_lua_tintaLua_executeBuffer
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    executeFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tinta_common_lua_tintaLua_executeFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    getGlobInteger
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_tinta_common_lua_tintaLua_getGlobInteger
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    getGlobBolean
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_tinta_common_lua_tintaLua_getGlobBolean
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    getGlobDouble
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_com_tinta_common_lua_tintaLua_getGlobDouble
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    getGlobString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tinta_common_lua_tintaLua_getGlobString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    getGlobFloat
 * Signature: (Ljava/lang/String;)F
 */
JNIEXPORT jfloat JNICALL Java_com_tinta_common_lua_tintaLua_getGlobFloat
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    getGlobIntArray
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_com_tinta_common_lua_tintaLua_getGlobIntArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    getGlobFloatArray
 * Signature: (Ljava/lang/String;)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_tinta_common_lua_tintaLua_getGlobFloatArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    getGlobDoubleArray
 * Signature: (Ljava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_tinta_common_lua_tintaLua_getGlobDoubleArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    getGlobBooleanArray
 * Signature: (Ljava/lang/String;)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_com_tinta_common_lua_tintaLua_getGlobBooleanArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    getGlobStringArray
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_tinta_common_lua_tintaLua_getGlobStringArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    stackSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tinta_common_lua_tintaLua_stackSize
  (JNIEnv *, jobject);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    getInt
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_tinta_common_lua_tintaLua_getInt
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    getDouble
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_com_tinta_common_lua_tintaLua_getDouble
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    getBoolean
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_tinta_common_lua_tintaLua_getBoolean
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    getFloat
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_com_tinta_common_lua_tintaLua_getFloat
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    getString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tinta_common_lua_tintaLua_getString
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    pushVal
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_tinta_common_lua_tintaLua_pushVal__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    pushVal
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_tinta_common_lua_tintaLua_pushVal__F
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    pushVal
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_com_tinta_common_lua_tintaLua_pushVal__D
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    pushVal
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_tinta_common_lua_tintaLua_pushVal__Z
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    pushVal
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tinta_common_lua_tintaLua_pushVal__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    setError
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tinta_common_lua_tintaLua_setError
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tinta_common_lua_tintaLua
 * Method:    error
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tinta_common_lua_tintaLua_error
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
